name: Tests

on:
  push

jobs:
  job:
    name: Test (Python ${{ matrix.python-ver }}, Pyright ${{ matrix.pyright-ver }}, NumPy ${{ matrix.numpy-ver }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-ver: [3.7, 3.8, 3.9]
        pyright-ver: [1.1.125, 1.1.126, 1.1.127]
        numpy-ver: [1.20.0, 1.20.1, 1.20.2]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-ver }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Install dependencies
        run: |
          pip install numpy==${{ matrix.numpy-ver }}
          npm install -g pyright@${{ matrix.pyright-ver }}
      - name: Static type check
        run: pyright repro.py
